server:
  port: 8899

spring:
  application:
    name: toolbox
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    com.toolbox: DEBUG
